package com.sunpower.scale.inventoryplane.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Warehouse {

    // Global Identifier of the warehouse across the systems. Generated by WMS?
    private String warehouseId;
    private String name;
    private String description;
    private Address address;
    private Contact contact;
}
